# Generated by Django 3.0.3 on 2020-02-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='librarian',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
